baseurl = "https://sec.alexflor.es"
title = "[audible]blink's \" r e s e a r c h \""

theme = "hello-friend-ng"
languageCode = "en-us"

googleAnalytics = "UA-12497311-8"
disqusShortname = "blinksec"
publishDir = "docs"

[permalinks]
  posts = "/posts/:year/:month/:title/"

[author]
  name = "[audible]blink"

[params]
  description = "blink's blog"
  keywords = "hacking, blog, science, infosec, development, programming"
  homeSubtitle = "Things have been OK for me except that I'm a zombie now"
  copyright = "Untitled."

  [params.logo]
    logoText     = "$ cd ~/"
    logoHomeLink = "/"

  [[params.social]]
    name = "github"
    url = "https://github.com/audibleblink"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/4lex"

  [[params.social]]
    name = "linkedin"
    url = "https://linkedin.com/in/alex2"

  [[params.social]]
    name = "keybase"
    url = "https://keybase.io/serveradmin"

[taxonomies]
  tag = "tags"
  category = "categories"

[menu]
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "posts/"
